import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { ALL } from "./data/cards.js";
import {
  ASSET_ROOT, CAT, CATEGORY_KEYS, FREE_CATEGORY_KEYS, PAID_CATEGORY_KEYS,
  UI_ASSETS, getEligibleCardIndexes,
} from "./data/game.js";
import { applyGameAction, buildCardOrder, createEmptyScores } from "./lib/room.js";

const STORAGE_KEY = "ekiki-gwe:active-game:v2";
const OLD_STORAGE_KEY = "ekiki-gwe:active-game:v1";
const ENTITLEMENT_KEY = "ekiki-gwe:after-hours:v1";
const SETTINGS_KEY = "ekiki-gwe:settings:v1";
const DEFAULT_SETTINGS = { sound: true, haptics: true, reduceMotion: false };
const REDEMPTION_CODE = "AFTERHOURS";
const AVATARS = ["lion", "leopard", "fox", "frog", "butterfly", "octopus", "jester", "fire", "moon", "lightning"]
  .map(name => `${ASSET_ROOT}/avatar-${name}.webp`);

const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Outfit:wght@400;600;700;900&display=swap');
*{box-sizing:border-box}html,body,#__next{margin:0;min-height:100%;background:#07070f}button,input{font:inherit}
body{overflow-x:hidden}.root{min-height:100vh;background:radial-gradient(ellipse at 25% 0%, #1a053a 0%, #07070f 55%);color:#fff;font-family:'Outfit',sans-serif;padding:1rem 1rem 2.5rem;position:relative;overflow:hidden}
.root:before{content:"";position:fixed;inset:-20%;pointer-events:none;background:radial-gradient(circle at 78% 18%,rgba(245,197,24,.08),transparent 24%),radial-gradient(circle at 12% 76%,rgba(178,75,243,.09),transparent 22%)}
.shell{width:min(100%,1040px);margin:auto;position:relative;z-index:1}.narrow{width:min(100%,470px);margin:auto}.logo,.display{font-family:'Bebas Neue',sans-serif;letter-spacing:.075em;line-height:.92}.eyebrow{font-size:.72rem;font-weight:900;letter-spacing:.18em;text-transform:uppercase;color:#F5C518}.muted{color:rgba(255,255,255,.55)}
.appbar{height:52px;display:grid;grid-template-columns:88px 1fr 88px;align-items:center;margin-bottom:1rem}.app-title{text-align:center;font-size:.72rem;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:rgba(255,255,255,.5)}
.icon-btn{min-height:40px;border:1px solid rgba(255,255,255,.14);border-radius:999px;background:rgba(255,255,255,.055);color:#fff;padding:.55rem .8rem;font-weight:800;font-size:.72rem;cursor:pointer}.icon-btn:hover{background:rgba(255,255,255,.1)}
.btn{border:0;border-radius:999px;min-height:52px;padding:.85rem 1.25rem;font-weight:900;letter-spacing:.025em;cursor:pointer;transition:transform .18s,filter .18s,opacity .18s}.btn:hover:not(:disabled){transform:translateY(-2px);filter:brightness(1.08)}.btn:disabled{cursor:not-allowed;opacity:.42}.btn-gold{color:#150b00;background:linear-gradient(135deg, #F5C518, #E8900A);box-shadow:0 12px 30px rgba(232,144,10,.2)}.btn-dark{color:#fff;background:rgba(255,255,255,.075);border:1px solid rgba(255,255,255,.13)}.btn-danger{color:#ffabb1;background:rgba(255,71,87,.12);border:1px solid rgba(255,71,87,.28)}
button:focus-visible,input:focus-visible,[role=button]:focus-visible{outline:3px solid #F5C518;outline-offset:3px}.panel{background:linear-gradient(160deg,rgba(255,255,255,.075),rgba(255,255,255,.025));border:1px solid rgba(255,255,255,.12);box-shadow:0 24px 70px rgba(0,0,0,.28);backdrop-filter:blur(12px)}
.setup-hero{padding:clamp(1.5rem,6vw,3rem) 0 1.6rem}.setup-title{font-size:clamp(4.7rem,20vw,8.6rem);margin:0;background:linear-gradient(135deg,#F5C518 20%,#FF6B35 70%);background-clip:text;-webkit-background-clip:text;color:transparent}.setup-kicker{font-size:clamp(1.1rem,4vw,1.5rem);font-weight:700;max-width:360px;line-height:1.35}.setup-card{border-radius:32px 32px 12px 32px;padding:1.2rem}.input-row{display:flex;gap:.55rem}.input{width:100%;min-width:0;border:1px solid rgba(255,255,255,.16);border-radius:16px;background:rgba(0,0,0,.24);color:#fff;padding:.85rem 1rem;outline:none}.input::placeholder{color:rgba(255,255,255,.34)}
.players{display:grid;gap:.5rem;margin-top:.9rem}.player{display:flex;align-items:center;gap:.7rem;border-bottom:1px solid rgba(255,255,255,.08);padding:.45rem 0}.avatar{border-radius:50%;overflow:hidden;background:rgba(255,255,255,.08);flex:0 0 auto}.player-name{flex:1;font-weight:800}.remove{border:0;background:transparent;color:rgba(255,255,255,.48);cursor:pointer;font-size:1.2rem}.helper{min-height:20px;margin:.7rem 0;font-size:.78rem}.responsible{text-align:center;color:rgba(255,255,255,.34);font-size:.72rem;margin-top:1rem}
.deck-head{display:grid;grid-template-columns:1fr auto;gap:1rem;align-items:end;margin:1.5rem 0}.deck-title{font-size:clamp(3.1rem,11vw,5.6rem);margin:.25rem 0 0}.deck-count{text-align:right}.deck-count strong{display:block;font:3rem/1 'Bebas Neue';color:#F5C518}.all-card{width:100%;border:1px solid rgba(245,197,24,.35);border-radius:12px 28px 12px 28px;background:linear-gradient(135deg,rgba(245,197,24,.16),rgba(232,144,10,.05));color:#fff;padding:1rem;display:flex;align-items:center;gap:.9rem;text-align:left;cursor:pointer;margin-bottom:1rem}.all-card.selected{box-shadow:inset 0 0 0 2px #F5C518}.all-copy{flex:1}.all-copy strong{display:block;font-size:1.02rem}.all-copy span{font-size:.74rem;color:rgba(255,255,255,.55)}
.deck-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem}.deck-card{position:relative;min-height:156px;border:1px solid rgba(255,255,255,.12);border-radius:10px 28px 10px 10px;background:rgba(255,255,255,.04);color:#fff;padding:.85rem;text-align:left;cursor:pointer;overflow:hidden}.deck-card:after{content:"";position:absolute;inset:auto -30px -50px auto;width:110px;height:110px;border-radius:50%;background:var(--cat);filter:blur(35px);opacity:.18}.deck-card.selected{border-color:var(--cat);box-shadow:inset 0 0 0 1px var(--cat),0 16px 38px rgba(0,0,0,.25)}.deck-card.locked{filter:saturate(.72)}.deck-icon{width:56px;height:56px;position:relative;z-index:1}.deck-name{display:block;font-weight:900;margin-top:.55rem;line-height:1.1;position:relative;z-index:1}.deck-meta{display:block;font-size:.7rem;color:rgba(255,255,255,.52);margin-top:.28rem;position:relative;z-index:1}.state-tag{position:absolute;right:.7rem;top:.7rem;font-size:.58rem;font-weight:900;letter-spacing:.1em;padding:.3rem .45rem;border-radius:999px;background:rgba(0,0,0,.36);z-index:2}.deck-actions{position:sticky;bottom:.7rem;margin-top:1rem;padding:.65rem;border-radius:999px;background:rgba(7,7,15,.86);backdrop-filter:blur(12px);display:flex;gap:.55rem}.deck-actions .btn{flex:1}
.pay-hero{text-align:center;padding:1rem 0 1.4rem}.pay-title{font-size:clamp(4rem,16vw,7rem);margin:.3rem 0}.pay-sub{max-width:520px;margin:auto;line-height:1.55}.expansion-grid{display:grid;gap:.75rem}.expansion-card{border-radius:10px 30px 10px 10px;padding:1rem;display:grid;grid-template-columns:62px 1fr;gap:.9rem;align-items:start}.example{font-size:.82rem;line-height:1.45;color:rgba(255,255,255,.72);margin:.45rem 0 0}.price-row{border-radius:28px 12px 28px 12px;padding:1rem;margin-top:1rem}.price{font:2rem/1 'Bebas Neue';letter-spacing:.06em}.redeem{display:flex;gap:.55rem;margin-top:.8rem}.status{min-height:22px;font-size:.78rem;margin-top:.55rem}
.play-shell{width:min(100%,520px);margin:auto}.turn{text-align:center;margin:.5rem 0}.turn-name{font-size:clamp(2.3rem,10vw,4rem);margin:.2rem 0}.progress-row{display:flex;align-items:center;gap:.7rem;margin-bottom:.8rem}.progress{height:4px;flex:1;background:rgba(255,255,255,.1);border-radius:4px;overflow:hidden}.progress>span{display:block;height:100%;background:linear-gradient(135deg, #F5C518, #E8900A)}
.scene{width:min(86vw,350px,calc((100vh - 320px)*.714));min-width:220px;aspect-ratio:5/7;margin:auto;perspective:1500px;cursor:pointer}.card-inner{width:100%;height:100%;position:relative;transform-style:preserve-3d;transition:transform .82s cubic-bezier(.16,.9,.22,1)}.card-inner.flipped{transform:rotateY(180deg) scale(1.02)}.face{position:absolute;inset:0;backface-visibility:hidden;-webkit-backface-visibility:hidden;border-radius:24px 52px 24px 24px;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:2rem;overflow:hidden}.face-front{background:linear-gradient(150deg,#210946,#090513);border:1px solid rgba(245,197,24,.35);box-shadow:0 34px 90px rgba(0,0,0,.62),inset 0 0 0 1px rgba(255,255,255,.04)}.face-front:before{content:"";position:absolute;inset:-70% -30%;background:linear-gradient(105deg,transparent 42%,rgba(245,197,24,.12) 50%,transparent 58%);transform:rotate(12deg);animation:sweep 3.3s ease-in-out infinite}.face-back{transform:rotateY(180deg);box-shadow:0 34px 90px rgba(0,0,0,.58);border:1px solid rgba(255,255,255,.18)}.card-brand{font:2rem/1 'Bebas Neue';letter-spacing:.19em;color:#F5C518}.tap{font-size:.72rem;font-weight:900;letter-spacing:.15em;text-transform:uppercase;color:rgba(255,255,255,.52);margin-top:1rem}.badge{display:flex;align-items:center;gap:.5rem;background:rgba(0,0,0,.24);padding:.45rem .75rem;border-radius:999px;font-size:.68rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.prompt{font-size:clamp(1rem,4.2vw,1.28rem);font-weight:800;line-height:1.5;text-align:center;margin-top:1.2rem;text-shadow:0 2px 10px rgba(0,0,0,.3)}.actions{display:flex;gap:.65rem;margin-top:1rem}.actions .btn{flex:1}.decision{text-align:center;margin-top:1rem;font-weight:900;color:#F5C518}
.result-head{text-align:center}.result-title{font-size:clamp(4rem,17vw,7rem);margin:.4rem 0}.podium{display:grid;gap:.65rem;margin:1rem 0}.score{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:.75rem;padding:.7rem;border-bottom:1px solid rgba(255,255,255,.1)}.score strong{font-size:1rem}.score span{font-size:.72rem;color:rgba(255,255,255,.5)}.score-total{font:2rem/1 'Bebas Neue';color:#F5C518}.result-actions{display:grid;gap:.6rem}
.modal-backdrop{position:fixed;inset:0;z-index:50;background:rgba(3,3,10,.82);display:grid;place-items:end center;padding:1rem;backdrop-filter:blur(10px)}.modal{width:min(100%,470px);border-radius:30px 30px 12px 12px;padding:1.2rem;background:#151020;border:1px solid rgba(255,255,255,.14)}.modal-head{display:flex;justify-content:space-between;gap:1rem;margin-bottom:1rem}.modal-title{font:2.1rem/1 'Bebas Neue';letter-spacing:.06em}.setting{display:flex;justify-content:space-between;gap:1rem;padding:.75rem 0;border-bottom:1px solid rgba(255,255,255,.08)}.switch{width:48px;height:28px;border:0;border-radius:999px;background:rgba(255,255,255,.15);padding:3px;cursor:pointer}.switch span{display:block;width:22px;height:22px;border-radius:50%;background:#fff;transition:transform .2s}.switch.on{background:#F5C518}.switch.on span{transform:translateX(20px)}
.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}@keyframes sweep{0%,35%{transform:translateX(-35%) rotate(12deg)}70%,100%{transform:translateX(35%) rotate(12deg)}}.reduce-motion *{animation:none!important;transition-duration:.01ms!important}
@media(min-width:700px){.deck-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.expansion-grid{grid-template-columns:repeat(3,1fr)}.expansion-card{grid-template-columns:1fr;min-height:245px}.modal-backdrop{place-items:center}.modal{border-radius:30px 12px 30px 12px}}
`;

function GameIcon({ src, alt = "", size = 32, className = "" }) {
  return <Image src={src} alt={alt} width={size} height={size} sizes={`${size}px`} className={className} style={{ objectFit: "contain" }} />;
}

function AppBar({ title, onBack, onMenu, menuLabel = "Settings" }) {
  return <div className="appbar"><div>{onBack && <button className="icon-btn" onClick={onBack}>Back</button>}</div><div className="app-title">{title}</div><div style={{ textAlign: "right" }}>{onMenu && <button className="icon-btn" onClick={onMenu}>{menuLabel}</button>}</div></div>;
}

function SetupScreen({ players, name, setName, addPlayer, removePlayer, next, error, settings, onSettings }) {
  return <Page settings={settings}><div className="narrow"><AppBar title="Ekiki Gwe" onMenu={onSettings} /><header className="setup-hero"><div className="eyebrow">Pass the phone. Tell the truth.</div><h1 className="setup-title display">EKIKI<br />GWE</h1><p className="setup-kicker">The party game that exposes everyone—and keeps the room moving.</p></header><section className="panel setup-card" aria-labelledby="players-title"><div className="eyebrow" id="players-title">Who is playing?</div><div className="input-row" style={{ marginTop: ".8rem" }}><input className="input" value={name} maxLength={20} aria-label="Player name" placeholder="Add a name" onChange={e => setName(e.target.value)} onKeyDown={e => { if (e.key === "Enter") addPlayer(); }} /><button className="btn btn-gold" onClick={addPlayer} disabled={!name.trim() || players.length >= 10}>Add</button></div><div className="players">{players.map((player, index) => <div className="player" key={player}><div className="avatar"><GameIcon src={AVATARS[index % AVATARS.length]} alt="" size={36} /></div><span className="player-name">{player}</span><button className="remove" aria-label={`Remove ${player}`} onClick={() => removePlayer(player)}>&times;</button></div>)}</div><div className="helper" aria-live="polite" style={{ color: error ? "#ff929b" : "rgba(255,255,255,.42)" }}>{error || `${players.length}/10 players · names must be unique`}</div><button className="btn btn-gold" style={{ width: "100%" }} disabled={players.length < 2} onClick={next}>{players.length < 2 ? "Add at least 2 players" : "Choose the decks"}</button></section><p className="responsible">Keep it consensual. Skip any card. Drink responsibly.</p></div></Page>;
}

function DeckScreen({ selected, entitled, toggle, selectAll, cardCount, start, back, openPaywall, settings, onSettings }) {
  const unlocked = entitled ? CATEGORY_KEYS : FREE_CATEGORY_KEYS;
  const allSelected = unlocked.every(key => selected.includes(key));
  return <Page settings={settings}><div className="shell"><AppBar title="Build Your Night" onBack={back} onMenu={onSettings} /><header className="deck-head"><div><div className="eyebrow">Mix your own chaos</div><h1 className="deck-title display">CHOOSE<br />YOUR DECKS</h1></div><div className="deck-count"><strong>{cardCount}</strong><span className="muted">cards ready</span></div></header><button className={`all-card${allSelected ? " selected" : ""}`} aria-pressed={allSelected} onClick={() => selectAll(unlocked)}><GameIcon src={UI_ASSETS.dice} size={48} /><span className="all-copy"><strong>Random / All</strong><span>One tap selects every {entitled ? "unlocked" : "free"} category</span></span><span className="state-tag">{allSelected ? "SELECTED" : "SELECT ALL"}</span></button><div className="deck-grid" role="group" aria-label="Choose one or more categories">{CATEGORY_KEYS.map(key => { const cat = CAT[key]; const locked = cat.tier === "paid" && !entitled; const active = selected.includes(key); const count = ALL.filter(card => card[0] === key).length; return <button key={key} className={`deck-card${active ? " selected" : ""}${locked ? " locked" : ""}`} style={{ "--cat": cat.color }} aria-pressed={active} aria-label={`${cat.label}, ${count} cards${locked ? ", locked in After Hours" : active ? ", selected" : ""}`} onClick={() => locked ? openPaywall() : toggle(key)}><span className="state-tag">{locked ? "AFTER HOURS" : active ? "IN" : "ADD"}</span><GameIcon src={cat.icon} alt="" size={56} className="deck-icon" /><span className="deck-name">{cat.label}</span><span className="deck-meta">{count} cards · {locked ? "locked" : active ? "tap to remove" : "tap to add"}</span></button>; })}</div><div className="deck-actions"><button className="btn btn-dark" onClick={openPaywall}>{entitled ? "After Hours unlocked" : "See After Hours"}</button><button className="btn btn-gold" onClick={start}>Play {cardCount} cards</button></div><p className="responsible">At least one deck always stays selected. Consent beats any card.</p></div></Page>;
}

function PaywallScreen({ back, redeem, restore, code, setCode, status, settings }) {
  return <Page settings={settings}><div className="shell"><AppBar title="Expansion" onBack={back} /><header className="pay-hero"><div className="eyebrow">Turn the lights down</div><h1 className="pay-title display">AFTER<br />HOURS</h1><p className="pay-sub muted">Three sharper decks. 180 cards built for couples, charged rooms, and groups that know how to check in before turning up.</p></header><div className="expansion-grid">{PAID_CATEGORY_KEYS.map(key => { const cat = CAT[key]; const example = ALL.find(card => card[0] === key)?.[1]; return <article className="panel expansion-card" key={key}><GameIcon src={cat.icon} alt="" size={62} /><div><div className="eyebrow" style={{ color: cat.color }}>60 cards</div><h2 style={{ margin: ".2rem 0", fontSize: "1.15rem" }}>{cat.label}</h2><p className="example">“{example}”</p></div></article>; })}</div><section className="panel price-row"><div className="eyebrow">One pack · all three decks</div><div className="price">Price announced at launch</div><p className="muted" style={{ fontSize: ".8rem", margin: ".45rem 0" }}>Payments are not live yet. Redeem the preview code <strong style={{ color: "#fff" }}>{REDEMPTION_CODE}</strong> to test the entitlement flow on this device.</p><div className="redeem"><input className="input" value={code} aria-label="Redemption code" placeholder="Redemption code" onChange={e => setCode(e.target.value)} /><button className="btn btn-gold" onClick={redeem}>Unlock</button></div><div className="status" aria-live="polite">{status}</div><button className="btn btn-dark" style={{ width: "100%", marginTop: ".25rem" }} onClick={restore}>Restore purchase</button></section></div></Page>;
}

function PlayScreen({ room, card, player, action, menu, leave, settings }) {
  const cat = CAT[card[0]]; const total = room.cardOrder.length; const progress = ((room.cardIdx + 1) / total) * 100;
  const reveal = () => { if (!room.flipped) action("flip"); };
  return <Page settings={settings}><div className="play-shell"><AppBar title={`${room.selectedCategories.length} decks in play`} onBack={leave} onMenu={menu} menuLabel="Menu" /><div className="progress-row"><span className="eyebrow">{room.cardIdx + 1} / {total}</span><div className="progress"><span style={{ width: `${progress}%` }} /></div></div><header className="turn"><div className="eyebrow">Your turn</div><h1 className="turn-name display" style={{ color: cat.color }}>{player.name}</h1></header><div className="scene" role="button" tabIndex={0} aria-label={room.flipped ? `${cat.label} card: ${card[1]}` : "Reveal the current card"} onClick={reveal} onKeyDown={e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); reveal(); } }}><div className={`card-inner${room.flipped ? " flipped" : ""}`}><div className="face face-front" aria-hidden={room.flipped}><div className="card-brand">EKIKI GWE</div><GameIcon src={UI_ASSETS.cardBack} alt="Face-down party card" size={105} /><div className="tap">Tap to reveal</div></div><div className="face face-back" aria-hidden={!room.flipped} style={{ background: cat.bg }}><div className="badge"><GameIcon src={cat.icon} alt="" size={26} />{cat.label}</div><div className="prompt">{card[1]}</div></div></div></div>{room.flipped && !room.decided && <div className="actions"><button className="btn btn-gold" onClick={() => action("did")}>I did it</button><button className="btn btn-dark" onClick={() => action("drank")}><GameIcon src={UI_ASSETS.drink} alt="" size={22} /> I’ll drink</button></div>}{room.decided && <div><div className="decision" aria-live="polite">Locked in. Pass the device.</div><button className="btn btn-gold" style={{ width: "100%", marginTop: ".7rem" }} onClick={() => action("next")}>{room.cardIdx === total - 1 ? "See final scores" : "Next player"}</button></div>}<p className="responsible">Anyone can skip. No explanations needed.</p></div></Page>;
}

function ResultScreen({ room, replay, changeDecks, exit, share, shareStatus, settings }) {
  const rows = [...room.players].sort((a, b) => { const as = room.scores[a.name]; const bs = room.scores[b.name]; return (bs.did - bs.drank) - (as.did - as.drank); });
  return <Page settings={settings}><div className="narrow"><AppBar title="Night Recap" /><header className="result-head"><GameIcon src={UI_ASSETS.trophy} alt="Trophy" size={86} /><div className="eyebrow">The room has spoken</div><h1 className="result-title display">EXPOSED</h1><p className="muted">{room.cardIdx + 1} cards · {room.selectedCategories.map(key => CAT[key].label).join(", ")}</p></header><section className="panel" style={{ borderRadius: "30px 10px 30px 10px", padding: ".75rem" }}>{rows.map(player => { const score = room.scores[player.name]; return <div className="score" key={player.id}><div className="avatar"><GameIcon src={player.avatar} alt="" size={42} /></div><div><strong>{player.name}</strong><br /><span>{score.did} did it · {score.drank} drank</span></div><div className="score-total">{score.did - score.drank}</div></div>; })}</section><div className="result-actions" style={{ marginTop: "1rem" }}><button className="btn btn-gold" onClick={replay}>Play again</button><button className="btn btn-dark" onClick={changeDecks}>Change decks</button><button className="btn btn-dark" onClick={share}>{shareStatus || "Share recap"}</button><button className="btn btn-danger" onClick={exit}>Exit game</button></div><div className="sr-only" aria-live="polite">{shareStatus}</div></div></Page>;
}

function Page({ children, settings }) { return <div className={`root${settings.reduceMotion ? " reduce-motion" : ""}`}><style jsx global>{CSS}</style>{children}</div>; }

function Modal({ title, onClose, children }) {
  useEffect(() => { const handler = e => { if (e.key === "Escape") onClose(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [onClose]);
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-head"><div id="modal-title" className="modal-title">{title}</div><button className="icon-btn" onClick={onClose}>Close</button></div>{children}</section></div>;
}

function SettingsModal({ settings, setSettings, close }) {
  return <Modal title="Settings" onClose={close}>{Object.entries({ sound: "Button sounds", haptics: "Vibration", reduceMotion: "Reduce motion" }).map(([key, label]) => <div className="setting" key={key}><span>{label}</span><button className={`switch${settings[key] ? " on" : ""}`} role="switch" aria-checked={settings[key]} aria-label={label} onClick={() => setSettings(current => ({ ...current, [key]: !current[key] }))}><span /></button></div>)}</Modal>;
}

function isValidStoredGame(game) {
  if (!game || !["play", "result"].includes(game.phase) || !Array.isArray(game.players) || game.players.length < 2 || game.players.length > 10) return false;
  if (!Array.isArray(game.selectedCategories) || game.selectedCategories.length === 0 || new Set(game.selectedCategories).size !== game.selectedCategories.length || game.selectedCategories.some(key => !CATEGORY_KEYS.includes(key))) return false;
  const eligible = getEligibleCardIndexes(ALL, game.selectedCategories);
  if (!Array.isArray(game.cardOrder) || game.cardOrder.length !== eligible.length || new Set(game.cardOrder).size !== eligible.length || game.cardOrder.some(index => !eligible.includes(index))) return false;
  if (!Number.isInteger(game.cardIdx) || game.cardIdx < 0 || game.cardIdx >= game.cardOrder.length || !Number.isInteger(game.playerIdx) || game.playerIdx < 0 || game.playerIdx >= game.players.length) return false;
  if (typeof game.flipped !== "boolean" || typeof game.decided !== "boolean" || !game.scores) return false;
  return game.players.every(player => player && typeof player.id === "string" && typeof player.name === "string" && game.scores[player.name] && Number.isInteger(game.scores[player.name].did) && Number.isInteger(game.scores[player.name].drank));
}

async function purchaseAfterHours(code) {
  await Promise.resolve();
  if (code.trim().toUpperCase() !== REDEMPTION_CODE) throw new Error("That preview code was not recognized.");
  window.localStorage.setItem(ENTITLEMENT_KEY, "unlocked");
  return true;
}

export default function EkikiGwe() {
  const [screen, setScreen] = useState("setup"); const [players, setPlayers] = useState([]); const [name, setName] = useState(""); const [error, setError] = useState("");
  const [selected, setSelected] = useState(FREE_CATEGORY_KEYS); const [entitled, setEntitled] = useState(false); const [room, setRoom] = useState(null); const [ready, setReady] = useState(false);
  const [settings, setSettings] = useState(DEFAULT_SETTINGS); const [overlay, setOverlay] = useState(null); const [code, setCode] = useState(""); const [purchaseStatus, setPurchaseStatus] = useState(""); const [shareStatus, setShareStatus] = useState("");

  useEffect(() => { try { window.localStorage.removeItem(OLD_STORAGE_KEY); const saved = JSON.parse(window.localStorage.getItem(STORAGE_KEY) || "null"); if (isValidStoredGame(saved)) { setRoom(saved); setPlayers(saved.players.map(player => player.name)); setSelected(saved.selectedCategories); setScreen("game"); } else window.localStorage.removeItem(STORAGE_KEY); setEntitled(window.localStorage.getItem(ENTITLEMENT_KEY) === "unlocked"); const savedSettings = JSON.parse(window.localStorage.getItem(SETTINGS_KEY) || "null"); if (savedSettings) setSettings({ ...DEFAULT_SETTINGS, ...savedSettings }); } catch { window.localStorage.removeItem(STORAGE_KEY); } finally { setReady(true); } }, []);
  useEffect(() => { if (!ready) return; try { if (room) window.localStorage.setItem(STORAGE_KEY, JSON.stringify(room)); else window.localStorage.removeItem(STORAGE_KEY); window.localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings)); } catch {} }, [room, settings, ready]);
  useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: "instant" }); }, [screen, room?.phase]);
  const cardCount = useMemo(() => getEligibleCardIndexes(ALL, selected).length, [selected]);
  const currentCard = room ? ALL[room.cardOrder[room.cardIdx]] : null; const currentPlayer = room?.players?.[room.playerIdx];
  const feedback = kind => { try { if (settings.haptics && navigator.vibrate) navigator.vibrate(kind === "success" ? [18, 35, 18] : 12); if (settings.sound && (window.AudioContext || window.webkitAudioContext)) { const Context = window.AudioContext || window.webkitAudioContext; const context = new Context(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.frequency.value = kind === "success" ? 660 : 440; gain.gain.setValueAtTime(.035, context.currentTime); gain.gain.exponentialRampToValueAtTime(.001, context.currentTime + .11); oscillator.connect(gain); gain.connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + .11); oscillator.onended = () => context.close(); } } catch {} };
  const addPlayer = () => { const clean = name.trim(); if (!clean) return; if (players.some(player => player.toLowerCase() === clean.toLowerCase())) return setError(`${clean} is already playing.`); if (players.length >= 10) return setError("A game can have up to 10 players."); setPlayers([...players, clean]); setName(""); setError(""); feedback("tap"); };
  const toggle = key => setSelected(current => current.includes(key) ? (current.length === 1 ? current : current.filter(item => item !== key)) : [...current, key]);
  const startGame = (names = players, categories = selected) => { const gamePlayers = names.map((player, index) => ({ id: `player-${index + 1}`, name: player, avatar: AVATARS[index % AVATARS.length] })); const seed = Math.floor(Math.random() * 1000000000); const eligible = getEligibleCardIndexes(ALL, categories); setRoom({ code: "LOCAL", players: gamePlayers, phase: "play", selectedCategories: [...categories], cardSeed: seed, cardOrder: buildCardOrder(seed, eligible), cardIdx: 0, playerIdx: 0, scores: createEmptyScores(gamePlayers), flipped: false, decided: false }); setScreen("game"); feedback("success"); };
  const sendAction = action => { setRoom(current => current ? applyGameAction(current, action, current.players[current.playerIdx]?.id) : current); feedback(action === "did" || action === "finish" ? "success" : "tap"); };
  const redeem = async () => { setPurchaseStatus("Checking code…"); try { await purchaseAfterHours(code); setEntitled(true); setSelected(current => [...new Set([...current, ...PAID_CATEGORY_KEYS])]); setPurchaseStatus("After Hours unlocked on this device."); feedback("success"); } catch (purchaseError) { setPurchaseStatus(purchaseError.message); } };
  const restore = () => { const restored = window.localStorage.getItem(ENTITLEMENT_KEY) === "unlocked"; setEntitled(restored); setPurchaseStatus(restored ? "Purchase restored on this device." : "No saved purchase was found on this device."); };
  const share = async () => { const lines = room.players.map(player => { const score = room.scores[player.name]; return `${player.name}: ${score.did} did it, ${score.drank} drank`; }); const text = `Ekiki Gwe night recap\n${room.cardIdx + 1} cards from ${room.selectedCategories.map(key => CAT[key].label).join(", ")}\n${lines.join("\n")}`; try { if (navigator.share) await navigator.share({ title: "Ekiki Gwe recap", text }); else await navigator.clipboard.writeText(text); setShareStatus(navigator.share ? "Shared" : "Copied"); } catch (shareError) { if (shareError.name !== "AbortError") setShareStatus("Share failed"); } window.setTimeout(() => setShareStatus(""), 1800); };
  const exit = () => { setRoom(null); setPlayers([]); setSelected(entitled ? CATEGORY_KEYS : FREE_CATEGORY_KEYS); setScreen("setup"); setOverlay(null); };
  const changeDecks = () => { setPlayers(room.players.map(player => player.name)); setSelected(room.selectedCategories); setRoom(null); setScreen("deck"); };
  const settingsView = overlay === "settings" ? <SettingsModal settings={settings} setSettings={setSettings} close={() => setOverlay(null)} /> : null;
  if (screen === "setup") return <><SetupScreen players={players} name={name} setName={value => { setName(value); setError(""); }} addPlayer={addPlayer} removePlayer={player => setPlayers(players.filter(item => item !== player))} next={() => setScreen("deck")} error={error} settings={settings} onSettings={() => setOverlay("settings")} />{settingsView}</>;
  if (screen === "deck") return <><DeckScreen selected={selected} entitled={entitled} toggle={toggle} selectAll={keys => setSelected([...keys])} cardCount={cardCount} start={() => startGame()} back={() => setScreen("setup")} openPaywall={() => setScreen("paywall")} settings={settings} onSettings={() => setOverlay("settings")} />{settingsView}</>;
  if (screen === "paywall") return <PaywallScreen back={() => setScreen("deck")} redeem={redeem} restore={restore} code={code} setCode={setCode} status={purchaseStatus} settings={settings} />;
  if (room?.phase === "play") return <><PlayScreen room={room} card={currentCard} player={currentPlayer} action={sendAction} leave={changeDecks} menu={() => setOverlay("menu")} settings={settings} />{overlay === "menu" && <Modal title="Game menu" onClose={() => setOverlay(null)}><div className="result-actions"><button className="btn btn-gold" onClick={() => setOverlay(null)}>Resume game</button><button className="btn btn-dark" onClick={() => setOverlay("settings")}>Settings</button><button className="btn btn-dark" onClick={() => { sendAction("finish"); setOverlay(null); }}>Finish &amp; score</button><button className="btn btn-danger" onClick={exit}>Exit game</button></div></Modal>}{settingsView}</>;
  return <ResultScreen room={room} replay={() => startGame(room.players.map(player => player.name), room.selectedCategories)} changeDecks={changeDecks} exit={exit} share={share} shareStatus={shareStatus} settings={settings} />;
}
